Repository benchttp/server, pull requests merged in 2022-03, with the labels that each got.

#13 feat: sync with benchttp/runner
  CONTRIBUTING.md
  benchttp/benchttp.go
  benchttp/repository.go
  cmd/main.go
  error.go
  error_internal_test.go
  firestore/report.go
  firestore/repository.go
  http/error.go
  http/handlers.go
  http/response.go
  http/server.go
  httplog/color.go
  httplog/request.go
  report.go
  repository.go
  routes.go
  server.go
  write.go
Labels: enhancement, must have

#16 doc: add main doc
  README.md
Labels: documentation

#22 Refactor/improve data layer structs and methods
  benchttp/stats.go
  routes.go
  services/postgresql/stats.go
  stats.go
Labels: enhancement

#23 feat: set up deployment
  .env.example
  .gcloudignore
  app.yaml
  cloudbuild.yaml
  cmd/main.go
  go.mod
  go.sum
  script/create-env
  server.go
Labels: must have
